# Generated by Django 6.0.3 on 2026-03-22 11:01

import django.core.validators
import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Скидка (%)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=7, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='season',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Сезон'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Категория')),
                ('sub_title', models.CharField(blank=True, help_text='прим. Рост 92–170', max_length=100, null=True, verbose_name='Дополнительный заголовок')),
                ('type', models.CharField(choices=[('level_1', 'Уровень 1'), ('category_2', 'Уровень 2'), ('category_3', 'Уровень 3'), ('category_4', 'Уровень 4')], max_length=255, verbose_name='Уровень категории')),
                ('icon_class', models.CharField(blank=True, help_text='Используется только для главной категории (прим. Мальчики)', max_length=100, null=True, verbose_name='Класс иконки')),
                ('icon_background_class', models.CharField(blank=True, help_text='Используется только для главной категории (прим. Мальчики)', max_length=100, null=True, verbose_name='Класс фона иконки')),
                ('fav_title', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Заголовок на вкладке')),
                ('main_title', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Главный заголовок')),
                ('keywords', models.CharField(blank=True, max_length=3000, null=True, verbose_name='Ключевые слова')),
                ('keywords_description', models.CharField(blank=True, max_length=3000, null=True, verbose_name='Meta описание')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.category', verbose_name='Отношение к категории одежды')),
            ],
            options={
                'verbose_name': 'Kатегория',
                'verbose_name_plural': 'Kатегории',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='store.category'),
        ),
    ]
