# Generated by Django 6.0.3 on 2026-03-22 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_seed_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sizeoption',
            options={'ordering': ['sort', 'value'], 'verbose_name': 'Размер', 'verbose_name_plural': 'Размеры'},
        ),
        migrations.AddField(
            model_name='sizeoption',
            name='age_label',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Возраст (подпись)'),
        ),
        migrations.AddField(
            model_name='sizeoption',
            name='sort',
            field=models.PositiveIntegerField(default=0, verbose_name='Сортировка'),
        ),
    ]
