# Generated by Django 6.0.3 on 2026-03-23 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('post', 'Почта'), ('europost', 'Европочта')], max_length=16)),
                ('last_name', models.CharField(blank=True, default='', max_length=150, verbose_name='Фамилия')),
                ('first_name', models.CharField(blank=True, default='', max_length=150, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, default='', max_length=150, verbose_name='Отчество')),
                ('phone', models.CharField(blank=True, default='', max_length=32, verbose_name='Телефон')),
                ('postal_index', models.CharField(blank=True, default='', max_length=16, verbose_name='Почтовый индекс')),
                ('city', models.CharField(blank=True, default='', max_length=64, verbose_name='Город')),
                ('street', models.CharField(blank=True, default='', max_length=128, verbose_name='Улица')),
                ('house', models.CharField(blank=True, default='', max_length=32, verbose_name='Дом')),
                ('apartment', models.CharField(blank=True, default='', max_length=32, verbose_name='Квартира')),
                ('europost_branch_number', models.CharField(blank=True, default='', max_length=32, verbose_name='Номер отделения Европочты')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'type'), name='uniq_address_per_user_per_type')],
            },
        ),
    ]
