# Generated by Django 6.0.3 on 2026-03-23 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_order_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='instagram',
            field=models.CharField(default='', help_text='Ник в Instagram для связи (например: username или @username).', max_length=64, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, db_index=True, default='', editable=False, max_length=32, unique=True, verbose_name='Номер заказа'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_sold',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Продан'),
        ),
        migrations.AddField(
            model_name='profile',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Отчество'),
        ),
    ]
