# Generated by Django 6.0.3 on 2026-03-23 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_order_instagram_order_order_number_product_is_sold_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_sold',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='availability',
            field=models.CharField(choices=[('available', 'Доступно'), ('reserved', 'В резерве'), ('sold', 'Продано')], db_index=True, default='available', max_length=16, verbose_name='Доступность'),
        ),
        migrations.AddField(
            model_name='product',
            name='reserved_until',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Резерв до'),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('available', 'В продаже'), ('reserved', 'В резерве'), ('sold', 'Продан')], db_index=True, default='available', max_length=16, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('confirmed', 'Подтверждён'), ('canceled', 'Отменён')], default='new', max_length=16, verbose_name='Статус заказа'),
        ),
    ]
