# Generated by Django 6.0.3 on 2026-03-31 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_remove_product_is_sold_cartitem_availability_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='ООО «Стиль-Няшки»', max_length=250, verbose_name='Наименование')),
                ('director', models.CharField(blank=True, default='Макодай А.П.', max_length=250, verbose_name='Руководитель')),
                ('legal_address', models.CharField(blank=True, max_length=512, null=True, verbose_name='Юридический адрес')),
                ('inn', models.CharField(blank=True, max_length=64, null=True, verbose_name='УНП / ИНН')),
                ('bank_account', models.CharField(blank=True, max_length=128, null=True, verbose_name='Расчетный счет (Р/с)')),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Банк (наименование)')),
                ('bank_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес банка')),
                ('bic', models.CharField(blank=True, max_length=64, null=True, verbose_name='БИК / SWIFT')),
                ('phone', models.CharField(blank=True, max_length=64, null=True, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Электронная почта')),
                ('registration_note', models.TextField(blank=True, null=True, verbose_name='Сведения о регистрации / режим работы')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'Информация о компании',
                'verbose_name_plural': 'Информация о компании',
            },
        ),
    ]
