# Generated by Django 6.0.3 on 2026-04-12 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_companyinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default=1, max_length=254, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'При получении (наложенный платеж)'), ('erip', 'АИС "Расчёт" (ЕРИП)'), ('card', 'Онлайн картой')], default='cod', max_length=16, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='store.category', verbose_name='Категория'),
        ),
    ]
