# Generated by Django 6.0.3 on 2026-04-12 13:35

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_order_email_order_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата оплаты'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128, verbose_name='ИД платежа (шлюз)'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Ожидается'), ('paid', 'Оплачен'), ('failed', 'Неудача'), ('refunded', 'Возврат')], default='pending', max_length=16, verbose_name='Статус оплаты'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(default='webpay', max_length=64, verbose_name='Платёжный шлюз')),
                ('gateway_payment_id', models.CharField(blank=True, db_index=True, default='', max_length=128, verbose_name='ИД в шлюзе')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Сумма')),
                ('currency', models.CharField(default='BYN', max_length=8, verbose_name='Валюта')),
                ('status', models.CharField(choices=[('pending', 'Ожидается'), ('paid', 'Оплачен'), ('failed', 'Неудача'), ('refunded', 'Возврат')], default='pending', max_length=16, verbose_name='Статус')),
                ('payload', models.JSONField(blank=True, null=True, verbose_name='Данные платежа (raw)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата оплаты')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='store.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Платёж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['-created_at'],
            },
        ),
    ]
