# Generated by Django 6.0.3 on 2026-04-12 16:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_order_paid_at_order_payment_id_order_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='retry_token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='Токен повторной оплаты'),
        ),
    ]
