# Generated by Django 6.0.3 on 2026-04-12 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_order_retry_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_cod', models.BooleanField(default=True, verbose_name='Наложенный платеж (COD)')),
                ('payment_erip', models.BooleanField(default=False, verbose_name='АИС «Расчёт» (ЕРИП)')),
                ('payment_card', models.BooleanField(default=False, verbose_name='Онлайн картой (Webpay)')),
            ],
            options={
                'verbose_name': 'Конфигурация сайта',
                'verbose_name_plural': 'Конфигурация сайта',
            },
        ),
    ]
