# Generated by Django 6.0.3 on 2026-05-13 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_alter_order_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='worktime',
            field=models.TextField(blank=True, null=True, verbose_name='Режим работы'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='registration_note',
            field=models.TextField(blank=True, null=True, verbose_name='Сведения о регистрации'),
        ),
    ]
