# Generated by Django 6.0.3 on 2026-05-25 18:59
from decimal import Decimal
from django.db import migrations, transaction

PRICE_MAP = {
    "50-74": Decimal("7"),
    "80-92": Decimal("7"),
    "98-104": Decimal("10"),
    "110-116": Decimal("10"),
    "122-128": Decimal("10"),
    "134-146": Decimal("12"),
    "152-158": Decimal("12"),
}

def set_product_prices(apps, schema_editor):
    Product = apps.get_model("store", "Product")
    with transaction.atomic():
        for p in Product.objects.prefetch_related("sizes").all():
            size_values = [s.value.strip() for s in p.sizes.all()]
            matched_prices = [PRICE_MAP[v] for v in size_values if v in PRICE_MAP]
            if not matched_prices:
                continue
            target_price = max(matched_prices)
            if p.price != target_price:
                p.price = target_price
                p.save(update_fields=["price"])


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_companyinfo_worktime_and_more'),
    ]

    operations = [
        migrations.RunPython(set_product_prices, reverse_code=migrations.RunPython.noop),
    ]
