# Generated by Django 6.0.3 on 2026-08-09 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_update_product_prices'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='token',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128, verbose_name='Токен платежной операции'),
        ),
    ]
