# Generated by Django 6.0.3 on 2026-08-15 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_payment_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Время истечения платежа (по умолчанию +60 минут от создания)', null=True, verbose_name='Платёж истекает в'),
        ),
    ]
